process_classification:
  work_processes:
  - msedgewebview2.exe
  - webviewhost.exe
  - applicationframehost.exe
  - runtimebroker.exe
  - electron.exe
  - searchhost.exe
  - winword.exe
  - excel.exe
  - powerpnt.exe
  - msaccess.exe
  - onenote.exe
  - onenotem.exe
  - visio.exe
  - project.exe
  - publisher.exe
  - pptview.exe
  - acrord32.exe
  - acrobat.exe
  - foxitpdfreader.exe
  - sumatrapdf.exe
  - pdfxedit.exe
  - nitropdf.exe
  - pdfelement.exe
  - mspub.exe
  - notepad.exe
  - notepad++.exe
  - wordpad.exe
  - sublime_text.exe
  - atom.exe
  - typora.exe
  - marktext.exe
  - obsidian.exe
  - logseq.exe
  - joplin.exe
  - evernote.exe
  - simplenote.exe
  - zettlr.exe
  - standardnotes.exe
  - sticky notes.exe
  - stikynot.exe
  - snippingtool.exe
  - screenclippinghost.exe
  - mspaint.exe
  - paintdotnet.exe
  - photos.exe
  - photoshop.exe
  - gimp-2.10.exe
  - krita.exe
  - inkscape.exe
  - calibre.exe
  - code.exe
  - cursor.exe
  - devenv.exe
  - vs_community.exe
  - rider64.exe
  - pycharm64.exe
  - idea64.exe
  - clion64.exe
  - webstorm64.exe
  - goland64.exe
  - datagrip64.exe
  - phpstorm64.exe
  - rubymine64.exe
  - fleet.exe
  - studio64.exe
  - eclipse.exe
  - netbeans64.exe
  - rstudio.exe
  - matlab.exe
  - spyder.exe
  - pyzo.exe
  - jupyterlab.exe
  - anaconda-navigator.exe
  - idle.exe
  - arduino.exe
  - codeblocks.exe
  - qtcreator.exe
  - emacs.exe
  - gvim.exe
  - vim.exe
  - cmd.exe
  - powershell.exe
  - pwsh.exe
  - wt.exe
  - windowsterminal.exe
  - bash.exe
  - wsl.exe
  - mintty.exe
  - putty.exe
  - kitty.exe
  - securecrt.exe
  - termius.exe
  - mobaxterm.exe
  - xshell.exe
  - winscp.exe
  - filezilla.exe
  - docker desktop.exe
  - docker.exe
  - kubectl.exe
  - helm.exe
  - terraform.exe
  - packer.exe
  - vagrant.exe
  - ansible.exe
  - python.exe
  - pythonw.exe
  - java.exe
  - javaw.exe
  - node.exe
  - npm.exe
  - yarn.exe
  - pnpm.exe
  - dotnet.exe
  - msbuild.exe
  - nuget.exe
  - gradle.exe
  - mvn.exe
  - cmake.exe
  - ninja.exe
  - make.exe
  - git.exe
  - gh.exe
  - glab.exe
  - svn.exe
  - hg.exe
  - tortoisegitproc.exe
  - tortoiseproc.exe
  - githubdesktop.exe
  - sourcetree.exe
  - gitkraken.exe
  - postman.exe
  - insomnia.exe
  - soapui.exe
  - fiddler.exe
  - wireshark.exe
  - procexp.exe
  - procmon.exe
  - powerbi.exe
  - tableau.exe
  - qliksense.exe
  - qlikview.exe
  - spss.exe
  - stata.exe
  - sas.exe
  - jmp.exe
  - minitab.exe
  - mathematica.exe
  - wolframkernel.exe
  - maple.exe
  - origin.exe
  - prism.exe
  - dbeaver.exe
  - pgadmin4.exe
  - mysqlworkbench.exe
  - sqlworkbench64.exe
  - ssms.exe
  - navicat.exe
  - heidisql.exe
  - robo3t.exe
  - mongodbcompass.exe
  - redis-desktop-manager.exe
  - figma.exe
  - canva.exe
  - illustrator.exe
  - afterfx.exe
  - premierepro.exe
  - lightroom.exe
  - indesign.exe
  - xd.exe
  - bridge.exe
  - animate.exe
  - audition.exe
  - coreldrw.exe
  - affinityphoto.exe
  - affinitydesigner.exe
  - affinitypublisher.exe
  - clipstudiopaint.exe
  - paintstormstudio.exe
  - blender.exe
  - unrealeditor.exe
  - unity.exe
  - godot.exe
  - sketchup.exe
  - fusion360.exe
  - acad.exe
  - revit.exe
  - inventor.exe
  - sldworks.exe
  - rhino.exe
  - cura.exe
  - prusa-slicer.exe
  - chitubox.exe
  - resolve.exe
  - vlc.exe
  - wmplayer.exe
  - audacity.exe
  - reaper.exe
  - fl64.exe
  - cubase.exe
  - protools.exe
  - streamlabs obs.exe
  - camtasia.exe
  - snagit64.exe
  - snagit32.exe
  - mstsc.exe
  - teamviewer.exe
  - anydesk.exe
  - parsec.exe
  - vncviewer.exe
  - rdcman.exe
  - vmware.exe
  - vmplayer.exe
  - virtualbox.exe
  - vboxmanage.exe
  - hypervmanager.exe
  - vmconnect.exe
  - citrixreceiver.exe
  - wfica32.exe
  - onedrive.exe
  - dropbox.exe
  - googledrivefs.exe
  - googledrivesync.exe
  - icloud.exe
  - box.exe
  - boxsync.exe
  - explorer.exe
  - taskmgr.exe
  - control.exe
  - systemsettings.exe
  - regedit.exe
  - mmc.exe
  - msconfig.exe
  - services.exe
  - perfmon.exe
  - resmon.exe
  - 7zfm.exe
  - winrar.exe
  - bandizip.exe
  - everything.exe
  - powertoys.exe
  - sharex.exe
  - greenshot.exe
  - lightshot.exe
  - nordvpn.exe
  - expressvpn.exe
  - protonvpn.exe
  - openvpn-gui.exe
  - wireguard.exe
  - ciscoanyconnect.exe
  - forticlient.exe
  - zscaler.exe
  - globalprotect.exe
  entertainment_processes:
  - obs64.exe
  - spotify.exe
  - itunes.exe
  - applemusic.exe
  - mpv.exe
  - potplayer64.exe
  - kmp.exe
  - mpc-hc64.exe
  - musicbee.exe
  - foobar2000.exe
  - plex.exe
  - jellyfin.exe
  - netflix.exe
  - primevideo.exe
  - steam.exe
  - epicgameslauncher.exe
  - battle.net.exe
  - goggalaxy.exe
  - ubisoftconnect.exe
  - eadesktop.exe
  - riotclientservices.exe
  - minecraftlauncher.exe
  - robloxplayerbeta.exe
  - leagueclient.exe
  - valorant.exe
  - cs2.exe
  - dota2.exe
  - fortniteclient-win64-shipping.exe
  - gta5.exe
  - rdr2.exe
  - eldenring.exe
  - starfield.exe
  - cyberpunk2077.exe
  - wow.exe
  - overwatch.exe
  - hearthstone.exe
  - hades.exe
  - stardewvalley.exe
  - factorio.exe
  - rimworldwin64.exe
  - terraria.exe
  - amongus.exe
  - rocketleague.exe
  - fallguys_client.exe
  - apex.exe
  - pubg.exe
  - rainbowsix.exe
  - destiny2.exe
  mixed_processes:
  - chrome.exe
  - msedge.exe
  - firefox.exe
  - brave.exe
  - opera.exe
  - opera_gx.exe
  - vivaldi.exe
  - maxthon.exe
  - waterfox.exe
  - palemoon.exe
  - seamonkey.exe
  - avastbrowser.exe
  - avgbrowser.exe
  - ccleanerbrowser.exe
  - yandex.exe
  - arc.exe
  - sidekick.exe
  - wavebox.exe
  - station.exe
  - ferdium.exe
  - franz.exe
  - webcatalog.exe
  - teams.exe
  - ms-teams.exe
  - ms-teams_modulehost.exe
  - slack.exe
  - discord.exe
  - zoom.exe
  - ciscojabber.exe
  - webex.exe
  - skype.exe
  - whatsapp.exe
  - signal.exe
  - telegram.exe
  - wechat.exe
  - line.exe
  - viber.exe
  - outlook.exe
  - olk.exe
  - thunderbird.exe
  - emclient.exe
  - mailbird.exe
  - mailspring.exe
  - postbox.exe
  - notion.exe
  - trello.exe
  - clickup.exe
  - monday.exe
  - ringcentral.exe
  - gotomeeting.exe
  - teamspeak.exe
  - mumble.exe
  - xournalpp.exe
  - drawboardpdf.exe
  - neovide.exe
  - neovim.exe
  - nvim-qt.exe
  - kate.exe
  - geany.exe
  - brackets.exe
  monitor_timeout: 2
